name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "docs/**"

permissions:
  contents: write

jobs:
  call-packaging-workflow:
    uses: ZachTheSplunker/app-wfa/.github/workflows/docs.yml@main