name: fossa
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths:
      - "SA-SentinelOneDevices/**"
    types: [opened, ready_for_review]

jobs:
  fossa-scan:
    name: Fossa Scan
    uses: splunk/oss-scanning-public/.github/workflows/oss-scan.yml@main
    secrets: inherit